[package]
name = "adblock-ffi"
version = "0.1.0"
authors = ["Huy Nguyen <huynq.cntt@gmail.com>"]
edition = "2018"

[dependencies]
adblock="~0.1.32"
libc = "0.2"

[lib]
crate-type = [
    "cdylib",
    "staticlib",
]
name = "adblock"

[features]
cbindgen = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
